# Generated by Django 3.0.5 on 2020-05-29 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tblcategory_tblsubcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblSubCategory',
        ),
    ]
