# Generated by Django 3.0.5 on 2020-05-29 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_tblsubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_name', models.CharField(max_length=50, unique=True)),
                ('Cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.TblCategory', to_field='category')),
            ],
        ),
    ]
