# Generated by Django 3.0.5 on 2020-05-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subcat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCat',
        ),
        migrations.DeleteModel(
            name='TblCategory',
        ),
    ]
